### ISSUE TITLE
bufferstream

### ISSUE THREAD

**Issue by AsakuraMizu** [ts-defold/type-gen#1]
According to the official document, bufferstream is an array-like object. And here is the source code: https://github.com/defold/defold/blob/869a87718757bdb7bfd6ed078047fa7bfb451de9/engine/gamesys/src/gamesys/scripts/script_buffer.cpp#L878

Any way to implement this feature?

**Comment by thejustinwalsh** [comment]
I could try to intersect the type with an array, and that would get you access to the `[]` index operator, but would also autocomplete a bunch of methods that are not available.

Worth a try though, let me dig in.

Any sample code of using this object I could test against?

**Comment by thejustinwalsh** [comment]
Using this as a scratchpad of thoughts,

 think I can support the "__index" and "__newIndex" method with something like:
```ts
declare type bufferstream = {
   [option: string]: any;
}
```

But to support the "#" operator, and array like access I would think it would be best to intersect an array:

```ts
declare type bufferstream = Array<number> & {
}
```

EDIT: This is what we will need here. At first glance the typescript support API around arrays should work too. Pay close attention to the caveats outline here:  https://typescripttolua.github.io/docs/caveats#array-length

**Comment by thejustinwalsh** [comment]
Additionally the documentation for buffer.create in the API is missing the return statement, will submit a PR, and figure out a patch in the meantime.

**Comment by thejustinwalsh** [comment]
Pending PR for documentation fix:
https://github.com/defold/defold/pull/5291

**Comment by thejustinwalsh** [comment]
fixed in c842bfa0ea4bad51eecacde6cce7f320524930ed

**Comment by AsakuraMizu** [comment]
OK it works now :clap:

<details>
<summary>Test code</summary>

`src/scripts/main.script.ts`:
```typescript
// @ts-ignore
go.property("res_dummy", resource.buffer("/main/dummy.buffer"))

interface props {
  res_dummy: buffer;
}

export function init(this: props): void {
  const dummy_str = String.fromCharCode(101, 97, 115, 116, 101, 114, 32, 101, 103, 103, 32, 109, 101, 100, 101, 108, 32, 111, 102, 32, 104, 111, 110, 111, 114, 32, 107, 101, 121, 32, 47, 97, 110, 100, 115, 118, 101, 32, 50, 48, 49, 57);
  const res_str = String.fromCharCode(...buffer.get_stream(resource.get_buffer(this.res_dummy), 'str').map(x => x));
  print(dummy_str);
  print(res_str);
}
```

`app/main/dummy.buffer`
```json
[
  {
    "name": "str",
    "type": "uint8",
    "count": 1,
    "data": [
      101,
      97,
      115,
      116,
      101,
      114,
      32,
      101,
      103,
      103,
      32,
      109,
      101,
      100,
      101,
      108,
      32,
      111,
      102,
      32,
      104,
      111,
      110,
      111,
      114,
      32,
      107,
      101,
      121,
      32,
      47,
      97,
      110,
      100,
      115,
      118,
      101,
      32,
      50,
      48,
      49,
      57
    ]
  }
]
```

</details>

Screenshot:  
![Screenshot_20201024_151627](https://user-images.githubusercontent.com/17076564/97070745-59afa000-160d-11eb-9d7d-8d4f2fd197eb.png)

Some further infomation:  
+ Why `// @ts-ignore`?  
  Unfortunately, it is another bug :(  
  `resource.buffer` (and `resource.font`, `resource.atlas` etc) should have an optional parameter, but none in the document.
+ Why `.map(x => x)`?  
  The spread operator (`...`) will be transformed to `unpack`, but this function accept only `table` (bufferstream is a `userdata`, even though it performs like a `table`), so I have to convert it to a `table` first.

**Comment by thejustinwalsh** [comment]
PR submitted https://github.com/defold/defold/pull/5299 for documentation fix.

**Comment by thejustinwalsh** [comment]
I don't understand why you need the .map(x => x) here either...

[This example](https://typescripttolua.github.io/play/#code/CYUwxgNghgTiAEAXAngBwQIwK4DMchgGdE4oBbeAXngEEYYpkAeAOyzIwID54AyeAN4AoAL4BuIUJxYWYRAEsA9i3gBzEIgD6xUmQAUASgBc8bHgI6Q5QUPh34cRFhgqA2gEYADO4A08AJwA7H7u7gCsIe4AbCHekQAsfgDMAEyxvvBeSbHZ8Kmx-umxnkWZngAcyWmZobHV+WWJNRmhJc0JVbHBZS0pGQ3x3UGRbV6j4ZGVPZ3wYW3xU-GFs4EAuhIikmDKxPBQRmb4RCRWFNSuo371fk0R8FHrQtssuxgHuEeW1ucAdH9QjyeO0Q8B0VHgAGUSPIWKofjgYIoyABhAAWsGRilAej+P3UWi++gMBiEqBgMMQeh0BjEQA) doesn't need the map to compile, does the map serve a purpose in the results, that I am not understanding:
```ts
declare type bufferstream = Array<number> & {
};

function get_stream(): bufferstream {
    return [101, 97, 115, 116, 101, 114, 32, 101, 103, 103, 32, 109, 101, 100, 101, 108, 32, 111, 102, 32, 104, 111, 110, 111, 114, 32, 107, 101, 121, 32, 47, 97, 110, 100, 115, 118, 101, 32, 50, 48, 49, 57];
}

const a:bufferstream = [0, 1, 2, 3, 4, 5, 6];
const b:bufferstream = [...a];

const str = String.fromCharCode(...get_stream())
print(str);
```

Is a bufferstream actually an object with the properties, name, type, count, data?
```ts
declare type bufferstream {
  name: string,
  type: string,
  count: number,
  data: Array<number>
}
```

**Comment by AsakuraMizu** [comment]
A small example about this:

src/scripts/main.script.ts:
```typescript
export function init(this: void): void {
  const b = buffer.create(1, [{ name: hash('example'), type: buffer.VALUE_TYPE_UINT8, count: 1 }]);
  const bs = buffer.get_stream(b, hash('example'));
  bs[0] = 1;
  pprint(bs);
  pprint(type(bs));
  pprint([...bs.map(x => x)]);
  pprint([...bs]);
}
```

app/scripts/main.script:
```lua
--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
-- Lua Library inline imports
function __TS__ArrayMap(arr, callbackfn)
    local newArray = {}
    do
        local i = 0
        while i < #arr do
            newArray[i + 1] = callbackfn(_G, arr[i + 1], i, arr)
            i = i + 1
        end
    end
    return newArray
end

local ____exports = {}
function ____exports.init()
    local b = buffer.create(
        1,
        {
            {
                name = hash("example"),
                type = buffer.VALUE_TYPE_UINT8,
                count = 1
            }
        }
    )
    local bs = buffer.get_stream(
        b,
        hash("example")
    )
    bs[1] = 1
    pprint(bs)
    pprint(
        type(bs)
    )
    pprint(
        {
            unpack(
                __TS__ArrayMap(
                    bs,
                    function(____, x) return x end
                )
            )
        }
    )
    pprint(
        {
            unpack(bs)
        }
    )
end
init = ____exports.init
```

And log:
```
DEBUG:SCRIPT: buffer.bufferstream({ hash("example"), buffer.VALUE_TYPE_UINT8, 1 })
DEBUG:SCRIPT: userdata
DEBUG:SCRIPT: 
{ --[[0x7fca11dbf910]]
  1 = 1
}
ERROR:SCRIPT: /scripts/main.script:48: bad argument #1 to 'unpack' (table expected, got userdata)
stack traceback:
	[C]: in function 'unpack'
	/scripts/main.script:48: in function </scripts/main.script:16>
```

In your example, `a` is a table in lua. But in Defold, `bs` is a userdata so that calling `unpack(bs)` will lead to an error.

**Comment by thejustinwalsh** [comment]
So after a good conversation with the folks over on the TypescriptToLua project, I don't think there is a perfect way to support the spread / destructing syntax without too many caveats and that the `.map(x => x)` may indeed be needed.

We could use a syntax like this but then we would lose access to the __len /  # length code generation and you would not be able to iterate through the generated code by index or determine it's length, but it appears that the `...` operator would work as well as `for .. of` syntax
```ts
type bufferstream = Pick<number[], keyof any[]> & {
    [Symbol.iterator](): IterableIterator<number>;
}
```

If we leave it as is, then you simply must do an extra step to destructure. Once the builtin replacement refactor is complete something like:
```ts
type bufferstream = Pick<number[], keyof any[] | "length"> & {
    [Symbol.iterator](): IterableIterator<number>;
}
```
could work as the length would resolve to the arrays property declaration.

I may be able to do some tricky syntax hacks on a plugin that could resolve this as well, but would prefer to wait for an update to the builtins...
https://discord.com/channels/515854149821267971/524910707079249960/770666461492150282

What I do not like about this is that the `...` operator produces valid syntax that does not error at compile time, and produces a runtime error instead. So from that perspective I will either be creating a lint rule to catch this, or using the alternative syntax and determining a way to get the length of the resource.

**Comment by thejustinwalsh** [comment]
Here are type declarations and a plugin to transform them. I will work on integrating dependencies across all projects, and publishing new types. But for now, this works in the tests included with the plugin. Stay tuned.

https://github.com/ts-defold/tstl-userdata-sugar

**Comment by thejustinwalsh** [comment]
Integrated into templates and updated types. Just need to expose resource types and I'll close this bug.

**Comment by AsakuraMizu** [comment]
Great work! I have nothing to say but there are some trailing space on [L45](https://github.com/ts-defold/tstl-userdata-sugar/blob/3fdffb1e6a5cb88205546cd86f57116d97405d1a/src/index.ts#L45) :smile:

**Comment by AsakuraMizu** [comment]
And it seems that a type regeneration is missed after merging defold/defold#5299.

**Comment by thejustinwalsh** [comment]
Haha, how did that sneak in?

**Comment by thejustinwalsh** [comment]
Added some overrides in d9ffbfa14e1d3df97ca370cf79f7d4a53c9c6fe3 until the docs are published for the new version and PR was accepted.
