### ISSUE TITLE
`var` keyword will generate invalid output

### ISSUE THREAD

**Issue by thinknathan** [ts-defold/type-gen#12]
Upcoming Defold v1.9.3 uses the `var` keyword as a parameter in its documentation: https://defold.com/ref/beta/types/#types.is_hash:var

Use of this reserved keyword is invalid in TypeScript: `SyntaxError: 'var' is not allowed as a parameter name.`

We should probably detect the `var` parameter and change it to `v`.

**Comment by thejustinwalsh** [comment]
Interesting choice for a parameter name, haha.
